apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: cluster-monitoring-config
    namespace: openshift-gitops
    annotations:
      argocd.argoproj.io/sync-wave: "10"
  spec:
    destination:
      server: https://kubernetes.default.svc
    project: default
    source:
      path: observability
      repoURL: https://github.com/bugbiteme/ossm3-from-from-scratch.git
      targetRevision: dev
    syncPolicy:
      automated:
        selfHeal: true
kind: List
metadata: {}
